### PR TITLE
Fix copyrights and links

### PR DESCRIPTION
**Pull request by hassanbazzi**
Just testing a pull request to your repo haha. Well.. These changes are needed but yea..

### CODE REVIEW

**Comment by scttcper** [comment]
Managed to make a merge conflict like always. Thanks.

**Comment by hassanbazzi** [comment]
haha! Sorry about that. If you have any plan for this or things that need to get done I can get some shit done and submit some more pull requests. I can do a ton of cool stuff UI wise and on the Angular layer.

**Comment by scttcper** [comment]
My fault. Uhhh I wanted to see a page to compare two players side by side somehow. There's also no /matches/, /heroes/, /items/, /player/ pages yet. That could be interesting as the backend doesn't support them either. The heroes and items data isn't really available from the hon api. It has missing items and the hero data is really difficult to parse and they already have decent pages on the official website. Whatever else you want to work on is cool too.

**Comment by hassanbazzi** [comment]
Awesome! If you want I can maybe create some issues so we can track some of these pages and features.

I'll contact the HoN team and see if we can improve the API. I bet they have some internal APIs to feed these pages.

**Comment by scttcper** [comment]
Issues would be cool. I wouldn't bother with hon team.There's bigger issues like the hon api has a global rate limit for all tokens and ip's.

**Pull request merged**
